### ISSUE TITLE
lack of version tag issue

### ISSUE THREAD

**Issue by yaroslavyaroslav** [jernejstrasner/SwiftCrypto#1]
When such package uses simultaneously in main package and in one of the dependencies package, swift package update cause the following error: 
`error: the package PoloneixConnection @ 0.0.2 contains revisioned dependencies: https://github.com/jernejstrasner/SwiftCrypto.git @ master`
Adding three signs version tag solves it. 

The bug is recursive, so when tag adds to e.g. SwiftCrypto such bug shows on its dependencies with branch("master")) either, e.g. CCommonCrypto.

When correct tags have been added for both of them command above works well.

**Comment by jernejstrasner** [comment]
Ha! Good to know! Adding tags now.
Thanks!

**Comment by jernejstrasner** [comment]
Will add tag to ea89d979867f6420885053736106e7c1e2139503
